CREATE TABLE IF NOT EXISTS Genres (
	id SERIAL PRIMARY KEY,
	name_genres VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Artist (
	id SERIAL PRIMARY KEY,
	name_artist VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Album (
	id SERIAL PRIMARY KEY,
	track VARCHAR(50) UNIQUE NOT NULL,
	release INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Track (
	id SERIAL PRIMARY KEY,
	name_track VARCHAR(50) UNIQUE NOT NULL,
	album INT NOT NULL REFERENCES Album(id)
);

CREATE TABLE IF NOT EXISTS Collections (
	id SERIAL PRIMARY KEY,
	name_collection VARCHAR(50) UNIQUE NOT NULL,
	release INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Artists_Album (
	id_album INT NOT NULL REFERENCES Album(id),
	id_musician INT NOT NULL REFERENCES Artist(id)
);

CREATE TABLE IF NOT EXISTS Collections_Track (
	id_collection INT NOT NULL REFERENCES Collections(id),
	id_track INT NOT NULL REFERENCES Track(id)
);

CREATE TABLE IF NOT EXISTS Genres_Artists (
	id_album INT NOT NULL REFERENCES Genres(id),
	id_musician INT NOT NULL REFERENCES Artist(id)
);